// Beauty Green Institut — Playwright config (template: .claude/templates/delivery-kit/ in the hub, process:
// knowledge/profiles/delivery.md). One story = one spec file under e2e/stories/ tagged @US-N;
// @smoke = the read-only subset replayed on prod after each deploy (P8).
import { defineConfig, devices } from "@playwright/test";

const baseURL = process.env.E2E_BASE_URL ?? "http://localhost:3000";

export default defineConfig({
  testDir: "e2e",
  // A flaky test is a defect, not a retry (the test guard refuses any retries increase).
  retries: 0,
  forbidOnly: !!process.env.CI,
  reporter: [
    ["list"],
    ["json", { outputFile: "playwright-report/results.json" }],
    ["html", { open: "never", outputFolder: "playwright-report/html" }],
  ],
  // Visual baselines (P7) are generated by CI and committed from its artifact, never from a
  // local machine (font rendering differs). A missing baseline makes its test fail (default mode).
  snapshotPathTemplate:
    "{testDir}/__snapshots__/{projectName}/{testFilePath}/{arg}{ext}",
  expect: {
    toHaveScreenshot: { maxDiffPixelRatio: 0.02, animations: "disabled" },
  },
  use: {
    baseURL,
    locale: "fr-FR",
    timezoneId: "Europe/Paris",
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    {
      name: "mobile-390",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 390, height: 844 },
        isMobile: true,
        hasTouch: true,
      },
    },
    {
      name: "desktop-1440",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 1440, height: 900 },
      },
      testIgnore: /layout-390\.spec\.ts/,
    },
  ],
  // Local stack only: when E2E_BASE_URL is set (prod smoke), no server is started.
  webServer: process.env.E2E_BASE_URL
    ? undefined
    : {
        command: "E2E_DRAFTS=1 pnpm build && pnpm start",
        url: "http://localhost:3000",
        reuseExistingServer: false,
        timeout: 300_000,
      },
});
